"""Preflop all-in matrix: what a sampled artifact has to prove before a lesson can cite it.

``pokergto.preflop`` samples boards and enumerates every dealable combo pair on each one, so the matrix is
exact *conditional* on the board set and the only error is board variance. That buys the 169x169 grid for
minutes instead of the ~740 hours exact enumeration costs (``adr/0006``), and it means this file has to hold
the checks that keep "sampled" from becoming "unchecked":

* the identities that are exact whatever the sample -- a class against itself is 0.5, and
  ``equity[i, j] + equity[j, i] == 1``. These run on a small board set, because a small board set is enough
  to prove an identity and the suite should not pay for statistics it is not testing;
* a closed-form check of the legality filter, because the probability that a four-card hole set survives a
  random five-card board is ``C(48,5) / C(52,5)``, which is arithmetic and not a simulation output;
* the error bar behaving like an error bar (``1 / sqrt(boards)``), and agreement with the three class cells
  that have been computed exactly -- both of which need real sample sizes and are marked ``slow``;
* determinism under a fixed seed, since a committed artifact that cannot be regenerated byte for byte is not
  a committed artifact.
"""

from __future__ import annotations

import math

import numpy as np
import pytest

from pokergto.cards import HAND_CLASSES_169, combos_for_class
from pokergto.errors import InputError
from pokergto.preflop import COMBO_CLASS, N_CLASSES, NONDEALABLE, all_in_matrix

#: 100 boards per batch is the engine's own floor, and 400 boards is enough to prove an identity: the
#: structural tests below assert things that are true at any sample size or not true at all.
FAST_BOARDS = 400
FAST_BATCHES = 4
FAST_SEED = 202_610_071


@pytest.fixture(scope="module")
def matrix():
    return all_in_matrix(FAST_BOARDS, seed=FAST_SEED, batches=FAST_BATCHES)


def _rows(key: str) -> np.ndarray:
    """Combo indices belonging to one of the 169 classes, straight off the engine's own mapping."""
    return np.flatnonzero(HAND_CLASSES_169.index(key) == COMBO_CLASS)


def test_a_class_against_itself_is_exactly_half(matrix) -> None:
    """``AA`` versus ``AA`` is a real deal (``AhAd`` against ``AsAc``), and it is a fair one.

    Every diagonal cell lands on 0.5 to the last bit and carries zero dispersion, because the two roles draw
    from the same class and the enumeration is symmetric in them. If a future change broke that -- by
    iterating pairs in one direction only, say -- the whole matrix would be wrong and no error bar would show
    it, which is why this is asserted rather than assumed.
    """
    assert np.all(np.diag(matrix.equity) == 0.5)
    assert np.all(np.diag(matrix.stderr) == 0.0)


def test_the_matrix_is_zero_sum_in_each_cell(matrix) -> None:
    """``equity[i, j] + equity[j, i] == 1`` exactly, not approximately.

    Ties are credited as half to each side, so the two directions have to partition the same pair set. This
    is an integer-level identity: a cell where it fails by even one comparison means the tie or the
    dealability mask was applied to one direction and not the other.
    """
    upper = np.triu_indices(N_CLASSES, 1)
    total = matrix.equity[upper] + matrix.equity.T[upper]
    assert np.all(total == 1.0), f"{int((total != 1.0).sum())} cells break the identity"
    assert np.all(matrix.pairs[upper] == matrix.pairs.T[upper]), (
        "the two directions must enumerate the same pair set"
    )


def test_ordered_cells_cover_the_whole_grid_including_the_diagonal(matrix) -> None:
    """169 x 169 = 28,561 cells, and none of them is an empty slot.

    The diagonal is populated for the same reason a class can be dealt against itself: two *different*
    combos. Asserting the count is what stops "sensible off-diagonal default" from quietly becoming the
    convention.
    """
    assert matrix.equity.shape == (N_CLASSES, N_CLASSES) == (169, 169)
    assert int(np.isfinite(matrix.equity).sum()) == N_CLASSES * N_CLASSES == 28_561
    assert int((matrix.pairs > 0).sum()) == N_CLASSES * N_CLASSES


def test_the_engine_refuses_a_sample_too_small_to_disperse() -> None:
    """The error bar is the artifact's honest part, so inputs that cannot support one are refused.

    ``batches`` is bounded by ``boards // 100`` for a reason: a batch of five boards measures board noise so
    coarsely that the spread of batch means is decoration, and a single batch has no spread at all.
    """
    with pytest.raises(InputError, match="under 100 boards"):
        all_in_matrix(50, seed=1)
    with pytest.raises(InputError, match="batches must be"):
        all_in_matrix(1_000, seed=1, batches=1)
    with pytest.raises(InputError, match="batches must be"):
        all_in_matrix(1_000, seed=1, batches=500)


def test_weighting_the_matrix_by_one_class_reproduces_that_column_exactly(matrix) -> None:
    """``equity_against`` is the same arithmetic as the matrix, so a one-hot weight must return it bit for bit.

    The function exists to answer "what is this class worth against a *range*", which is what a threshold
    decision compares. If it drifted from the stored cells even slightly, a lesson could quote an equity
    that no cell in the artifact supports -- so this is an exact equality, not an approximation.
    """
    for column in (0, 1, 100, 168):
        weights = np.zeros(N_CLASSES)
        weights[column] = 1.0
        equity, stderr = matrix.equity_against(weights)
        assert np.array_equal(np.nan_to_num(equity), np.nan_to_num(matrix.equity[:, column]))
        # The error bar has to match too, not just the estimate. This assertion is what caught an
        # `sqrt(batches)` scaling copied from the pair-count formula into a ratio: it inflated every range
        # error bar twentyfold and still passed the weaker "sigma is non-negative" check it replaced.
        assert np.array_equal(np.nan_to_num(stderr), np.nan_to_num(matrix.stderr[:, column]))


def test_the_range_error_bar_sits_between_the_naive_formula_and_a_single_cell(matrix) -> None:
    """A weighted row is neither "independent cells" nor "one cell" -- both ends are asserted.

    Every cell in a row is computed against the same boards, so they are correlated and the aggregate spread
    is **wider** than quadrature of the per-cell sigmas. Averaging over 168 opponents still helps, so it stays
    **narrower** than a single cell's sigma. The upper bound is the one that paid for itself: an
    ``sqrt(batches)`` scaling copied from the pair-count formula into a ratio made every aggregate twenty
    times too wide, which passed the one-sided check it replaced and is impossible under this one.

    Measured at 600 boards in 6 batches: aggregate / naive ratio 6.15 mean and 9.92 worst, against the
    perfectly-correlated ceiling of ``sqrt(168) = 12.96``; aggregate sigma 0.0098 versus a 0.0167 mean cell
    sigma.
    """
    weights = np.array([combos_for_class(key) for key in HAND_CLASSES_169], dtype=float)
    weights /= weights.sum()
    _, aggregate = matrix.equity_against(weights)
    naive = np.sqrt((matrix.stderr**2) @ (weights**2))
    ratio = aggregate / np.maximum(naive, 1e-12)
    assert float(np.nanmax(ratio)) > 1.2, (
        "the aggregate collapsed onto the independent-cells formula"
    )
    assert float(np.nanmax(ratio)) <= np.sqrt(N_CLASSES), (
        f"aggregate error bar beyond what board correlation can explain: {np.nanmax(ratio):.1f}"
    )
    assert float(np.nanmean(aggregate)) < float(np.nanmean(matrix.stderr)), (
        "averaging over opponents has to help, or the aggregation is not averaging"
    )


def test_cell_lookup_and_its_failure(matrix) -> None:
    with pytest.raises(InputError, match="unknown hand class"):
        matrix.cell("AZ", "AA")
    value, error = matrix.cell("AA", "KK")
    assert 0.0 < value < 1.0
    assert error > 0.0


def test_the_same_seed_reproduces_the_same_bytes(matrix) -> None:
    """ADR-0002's determinism rule applies to sampled artifacts first of all.

    The seed is the artifact's identity: the same ``seed``, ``boards`` and ``batches`` reproduce every value
    to the last bit, so ``gen_all --check`` stays a byte diff and a reviewer can regenerate a number they
    doubt. A different seed must move the numbers, or the seed is not being used.
    """
    again = all_in_matrix(FAST_BOARDS, seed=FAST_SEED, batches=FAST_BATCHES)
    assert np.array_equal(matrix.equity, again.equity)
    assert np.array_equal(matrix.stderr, again.stderr)
    assert np.array_equal(matrix.pairs, again.pairs)
    assert np.array_equal(matrix.pairs_stderr, again.pairs_stderr)
    other = all_in_matrix(200, seed=FAST_SEED + 1, batches=2)
    assert not np.array_equal(
        matrix.equity[np.triu_indices(N_CLASSES, 1)],
        other.equity[np.triu_indices(N_CLASSES, 1)],
    ), "a different seed must move the numbers"


#: Class cells computed exactly by ``range_equity(hero, villain, (), mode="exact")`` with the budget
#: raised, on the author's laptop 2026-10-07: 142.6 s, 176.8 s and 177.5 s. These are the anchors that make
#: "sampled" a claim with something under it, and the slow test below is what keeps them load-bearing.
EXACT_CELLS = {
    ("AA", "KK"): 0.819_460_504_7,
    ("AKo", "QQ"): 0.432_423_360_6,
    ("72o", "22"): 0.325_892_384_4,
}


@pytest.mark.slow
def test_pairs_survive_the_board_filter_by_closed_form_not_by_trusting_the_sample() -> None:
    """Dealable pair counts against ``C(48,5) / C(52,5)``, which is arithmetic rather than a simulation.

    For a fixed pair of hole combos sharing no card, the four cards must all miss a uniformly drawn five-card
    board, which happens with probability ``C(48,5) / C(52,5) = 1,712,304 / 2,598,960 = 0.65884200``. So the
    expected pair count is ``boards x dealable_pairs x that_probability``.

    The tolerance is the matrix's own **measured** dispersion of the denominator, not a binomial formula on
    the pair count. That distinction is the lesson this test paid for: comparisons sharing a board are
    correlated, and the first version of this test assumed independence, flagged a real 1.6-sigma deviation
    as "6.2 sigma" and would have had me chase a bug that did not exist. For ``AA`` v ``KK`` the exact
    per-board variance is available in closed form (sum over the hypergeometric ace/king counts), so the
    test also checks the empirical error bar against it -- an artifact's sigma has to be right too, not just
    present.
    """
    matrix = all_in_matrix(2_000, seed=31, batches=20)
    survival = math.comb(48, 5) / math.comb(52, 5)
    assert survival == pytest.approx(0.658_842_0, abs=1e-7)
    for hero, villain in (("AA", "KK"), ("72o", "22"), ("AKs", "QQ")):
        hero_rows = _rows(hero)
        villain_rows = _rows(villain)
        # NONDEALABLE is the conflict mask, so dealable pairs are its complement: AA versus KK has 36
        # ordered pairs and none of them share a card -- reading that mask backwards is the mistake this
        # line caught on its first run.
        dealable = int((~NONDEALABLE[np.ix_(hero_rows, villain_rows)]).sum())
        expected = matrix.boards * dealable * survival
        i, j = HAND_CLASSES_169.index(hero), HAND_CLASSES_169.index(villain)
        got, spread = matrix.pairs[i, j], matrix.pairs_stderr[i, j]
        assert spread > 0
        assert abs(got - expected) < 5 * spread, (
            f"{hero} v {villain}: got {got:,.0f}, closed form {expected:,.0f}, "
            f"{abs(got - expected) / spread:.1f} measured sigma"
        )
    exact_sigma = _analytic_pairs_sigma("AA", "KK", matrix.boards)
    ratio = matrix.pairs_stderr[0, HAND_CLASSES_169.index("KK")] / exact_sigma
    assert 0.6 < ratio < 1.6, f"empirical denominator sigma is {ratio:.2f}x the closed-form one"


def _analytic_pairs_sigma(hero: str, villain: str, boards: int) -> float:
    """Exact standard deviation of one cell's pair count over ``boards`` uniform five-card boards.

    Written out for the pocket-pair case because it is small enough to be arithmetic rather than
    simulation: a board showing ``a`` of hero's rank and ``k`` of villain's leaves ``C(4-a,2) x C(4-k,2)``
    legal ordered pairs, and the ``(a, k)`` counts follow the multivariate hypergeometric. The
    cross-moments of the resulting per-board counts give the variance, and independent boards add.
    """
    from math import comb

    total = comb(52, 5)
    first = second = 0.0
    for a in range(5):
        for k in range(5 - a):
            probability = comb(4, a) * comb(4, k) * comb(44, 5 - a - k) / total
            count = comb(4 - a, 2) * comb(4 - k, 2)
            first += probability * count
            second += probability * count * count
    return math.sqrt(boards * (second - first * first))


@pytest.mark.slow
def test_the_error_bar_shrinks_like_a_sampled_number_should() -> None:
    """Quadrupling the boards must roughly halve the standard error, or the batches are not independent.

    The ratio is expected near 2.0 (``1 / sqrt(4)``). If a refactor made the batches overlap, this collapses
    toward 1 and the error bar printed in the artifact becomes decoration.
    """
    small = all_in_matrix(400, seed=7, batches=4)
    large = all_in_matrix(1_600, seed=11, batches=16)
    i, j = HAND_CLASSES_169.index("AA"), HAND_CLASSES_169.index("KK")
    ratio = small.stderr[i, j] / large.stderr[i, j]
    assert 1.3 < ratio < 3.2, f"stderr ratio {ratio:.2f}, expected near 2.0"
    off_diagonal = ~np.eye(N_CLASSES, dtype=bool)
    assert np.all(large.stderr[off_diagonal] > 0)


@pytest.mark.slow
def test_the_sampled_matrix_agrees_with_the_exact_cells_within_its_own_error_bars() -> None:
    """8,000 boards (about 3.5 minutes) against cells enumerated over all 2,598,960.

    The assertion is a multiple of the matrix's *reported* standard error, so the test also verifies the
    error bar: an estimator off by more than four of its own sigmas is either biased or lying about its
    dispersion, and both are failures worth a red build. Measured deviations at this size ran 0.5 to 1.9
    sigma.
    """
    matrix = all_in_matrix(8_000, seed=202_610_072, batches=20)
    for (hero, villain), reference in EXACT_CELLS.items():
        value, error = matrix.cell(hero, villain)
        assert abs(value - reference) <= 4.0 * error, (
            f"{hero} v {villain}: sampled {value:.6f} vs exact {reference:.6f}, "
            f"{abs(value - reference) / error:.1f} sigma"
        )
