#!/usr/bin/env python3
"""Copy ``data/gen`` into the trainer and stamp the build with the version it was copied from.

ADR-0004: the trainer is a *consumer* of committed artifacts. It contains no poker mathematics, so the
numbers on screen are the numbers in the repository, and a mismatch between the two is a build failure
rather than a silently wrong chart. This tool is the only permitted bridge between the two trees.

It writes two things, both gitignored build products:

``trainer/public/data/**``
    A byte-for-byte copy of the artifact tree, so a fetch of ``/data/tables/x.json`` resolves offline
    on GitHub Pages under ``/trainer/`` and needs no backend.

``trainer/src/generated/manifest.ts``
    The digests and versions the app checks itself against at startup. A stale copy of the data tree
    then shows up as a thrown error in the console instead of a plausible-looking wrong number.

``--check`` performs the same comparison without writing, which is what CI runs: it proves the committed
tree and the committed trainer still agree, and it fails if the app was built against data that has
since changed.

Usage::

    python tools/sync_trainer_data.py            # write
    python tools/sync_trainer_data.py --check    # verify, write nothing
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
from pathlib import Path
from typing import Any

from _bootstrap import REPO_ROOT, bootstrap_path, fail, ok

bootstrap_path()

GEN = REPO_ROOT / "data" / "gen"
TRAINER = REPO_ROOT / "trainer"
PUBLIC_DATA = TRAINER / "public" / "data"
MANIFEST_TS = TRAINER / "src" / "generated" / "manifest.ts"

#: Extensions the trainer is allowed to read. Everything else in ``data/gen`` (the nav fragment, say)
#: belongs to mkdocs and has no business in a browser bundle.
CONSUMED_SUFFIXES = (".json", ".csv")

#: Files that describe the tree rather than teach from it, so they are not copied into the bundle.
SKIP_RELATIVES = ("manifest.json",)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _relatives(root: Path) -> list[str]:
    found = [
        path.relative_to(root).as_posix()
        for path in root.rglob("*")
        if path.is_file() and path.suffix in CONSUMED_SUFFIXES
    ]
    return sorted(name for name in found if name not in SKIP_RELATIVES)


def build_manifest(gen_dir: Path = GEN) -> dict[str, Any]:
    """The version stamp the app compares against, derived from the committed tree.

    ``schema_version`` and ``engine_version`` come from ``data/gen/manifest.json`` rather than from a
    constant here, because a generator that bumped its schema must not be able to ship a trainer that
    still claims the old one.
    """
    registry_manifest = gen_dir / "manifest.json"
    if not registry_manifest.exists():
        raise SystemExit(
            "data/gen/manifest.json is missing; run `python tools/gen_all.py` before syncing the "
            "trainer (ADR-0001: the artifacts are generated, not committed by hand)"
        )
    payload = json.loads(registry_manifest.read_text(encoding="utf-8"))
    return {
        "schema_version": str(payload["schema_version"]),
        "engine_version": str(payload["engine_version"]),
        "artifact_count": len(_relatives(gen_dir)),
        "files": {name: _sha256(gen_dir / name) for name in _relatives(gen_dir)},
    }


def render_manifest_ts(manifest: dict[str, Any]) -> str:
    """Render the TypeScript module.

    ``sort_keys`` and a fixed indent are not cosmetics: this file is compared byte-for-byte by
    ``--check``, so any formatting drift would read as a data change.
    """
    body = json.dumps(manifest, sort_keys=True, indent=2, ensure_ascii=True)
    return (
        "// Generated by tools/sync_trainer_data.py. Do not edit and do not commit (ADR-0004).\n"
        "// Editing this file by hand is how a trainer ends up reporting numbers that no engine\n"
        "// produced, which is the failure mode the whole repository is arranged to prevent.\n\n"
        f"export const MANIFEST = {body} as const;\n\n"
        "export type Manifest = typeof MANIFEST;\n"
    )


def _drift(expected: str, target: Path) -> str | None:
    if not target.exists():
        return f"{target.relative_to(REPO_ROOT).as_posix()} is missing"
    if target.read_text(encoding="utf-8") != expected:
        return f"{target.relative_to(REPO_ROOT).as_posix()} differs from what data/gen says"
    return None


def _verify(manifest: dict[str, Any]) -> list[str]:
    """Every reason the trainer's copy is not the committed tree, computed from disk as it stands."""
    problems: list[str] = []
    for name, digest in sorted(manifest["files"].items()):
        copy = PUBLIC_DATA / name
        if not copy.exists():
            problems.append(f"trainer/public/data/{name} is missing")
        elif _sha256(copy) != digest:
            problems.append(f"trainer/public/data/{name} differs from data/gen")
    present = (
        {
            path.relative_to(PUBLIC_DATA).as_posix()
            for path in PUBLIC_DATA.rglob("*")
            if path.is_file()
        }
        if PUBLIC_DATA.exists()
        else set()
    )
    problems.extend(
        f"trainer/public/data/{name} is stale (no such artifact in data/gen)"
        for name in sorted(present - set(manifest["files"]))
    )
    stamp = _drift(render_manifest_ts(manifest), MANIFEST_TS)
    if stamp:
        problems.append(stamp)
    return problems


def sync(*, check: bool) -> int:
    if not TRAINER.exists():
        ok("no trainer/ directory yet (pre-M3 state): nothing to sync")
        return 0
    if not GEN.exists():
        fail("data/gen does not exist; run `python tools/gen_all.py` first")
        return 1

    manifest = build_manifest()

    if not check:
        for name, digest in sorted(manifest["files"].items()):
            source = GEN / name
            copy = PUBLIC_DATA / name
            if not copy.exists() or _sha256(copy) != digest:
                copy.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(source, copy)
        if PUBLIC_DATA.exists():
            for path in PUBLIC_DATA.rglob("*"):
                if (
                    path.is_file()
                    and path.relative_to(PUBLIC_DATA).as_posix() not in manifest["files"]
                ):
                    path.unlink()
        MANIFEST_TS.parent.mkdir(parents=True, exist_ok=True)
        MANIFEST_TS.write_text(render_manifest_ts(manifest), encoding="utf-8", newline="\n")

    problems = _verify(manifest)
    for problem in problems[:20]:
        fail(f"out of sync: {problem}")
    if problems:
        print(
            "\nThe trainer is built against artifacts that are no longer the ones in data/gen.\n"
            "Run `python tools/sync_trainer_data.py` and rebuild the trainer.\n"
            "See docs/development/data-provenance.md and adr/0004.",
            file=sys.stderr,
        )
        return 1

    if check:
        ok(
            f"trainer data: {manifest['artifact_count']} artifacts match data/gen "
            f"(schema {manifest['schema_version']}, engine {manifest['engine_version']})"
        )
    else:
        ok(
            f"trainer data: copied {manifest['artifact_count']} artifacts and stamped "
            f"src/generated/manifest.ts"
        )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true", help="verify without writing (the CI mode)")
    return sync(check=parser.parse_args(argv).check)


if __name__ == "__main__":
    raise SystemExit(main())
